directories:
  output: release
  buildResources: build
appId: com.yaj.jwscheduler
productName: jwscheduler
files:
  - filter:
      - main.js
      - package.json
      - JSchedulerW_backend/**/*
      - JSchedulerW_frontend/dist/**/*
win:
  target:
    - nsis
    - portable
linux:
  target:
    - AppImage
    - deb
electronVersion: 40.8.0
